name: Dev build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches-ignore:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
# Prepare custom build version
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        #image-ref: ghcr.io/${{ github.repository }}:${{ steps.release_ver.outputs.value }}
        mage-ref: ghcr.io/th2-net/th2-codec-sailfish:3.13.0-th2-4253-jar-publishing-3515151579-f14beb2  
        severity: 'CRITICAL,HIGH,MEDIUM'
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '0'
        ignore-unfixed: false
        vuln-type: 'os,library'
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'        
